# Usa una imagen base de Node.js basada en Alpine
FROM node:20-alpine

# Instala dependencias necesarias
RUN apk add --no-cache \
    bash \
    xvfb \
    nss \
    freetype \
    harfbuzz \
    ttf-freefont \
    chromium \
    curl \
    fontconfig \
    libx11 \
    libxcomposite \
    libxdamage \
    libxext \
    libxi \
    libxtst \
    alsa-lib \
    cairo \
    cups-libs \
    dbus-libs \
    expat \
    flac \
    gdk-pixbuf \
    glib \
    libgcc \
    libjpeg \
    libpng \
    libwebp \
    libxrandr \
    libxrender \
    libxslt \
    libxt \
    pango \
    snappy \
    xdg-utils \
    && rm -rf /var/cache/apk/*

# Establece el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copia el package.json y el package-lock.json (si existe)
COPY package*.json ./

# Instala las dependencias de la aplicación
RUN npm install

# Instala los navegadores de Playwright
RUN npx playwright install --with-deps

# Copia el resto de los archivos de la aplicación
COPY . .

# Compila el código TypeScript
RUN npm run compile

# Expone el puerto en el que la aplicación se ejecutará
EXPOSE 3000

# Comando para ejecutar la aplicación
CMD ["npm", "start"]