name: publish

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_TOKEN }}

      - name: Build image
        run: | 
          docker build . --tag ghcr.io/ehloq/dream-captcher:latest .
          docker push ghcr.io/ehloq/dream-captcher:latest

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install --y sshpass

      - name: SSH into Server
        run: |
          sshpass -p ${{ secrets.AUTH_PASS }} ssh -o StrictHostKeyChecking=no ${{ secrets.AUTH_SERVER }} << EOF
          cd /root/dream-captcher
          docker login ghcr.io -u ehloq -p ${{ secrets.DEPLOY_TOKEN }}
          docker pull ghcr.io/ehloq/dream-captcher:latest
          docker stop dream-captcher && docker rm dream-captcher
          docker run -d \
            --name dream-captcher \
            -p 3000:3000 \
            -v /root/dream-captcher:/app \
            ghcr.io/ehloq/dream-captcher:latest